image:
  file: Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8002
  - port: 9001
  - port: 15672

tasks:
  - name: "Services"
    command: service nginx start &
            cd /workspace/magento2gitpod && /usr/sbin/php-fpm7.4 --fpm-config php-fpm.conf &
            sudo supervisord &
